# ma entrance examination 1400 (Statistics)
### Problems: 65, 66, 67, 68, 69, 70

<br><br><br>

### Problem 70: 

$$
\begin{aligned}
& X \sim \text{Unif}(0, 1), ~~\text{if}\quad Y = \begin{cases}1 & X \geq a, \\ 0 & X < a,\end{cases}\quad \text{and}~~ 0 < a < 1 \implies \\
& \max \text{Corr}(X, Y) = ?
\end{aligned}
$$

### Answer
<br><Br>

$$
\begin{aligned}
& \text{Corr}(X, Y) = \frac{\text{Cov}(X, Y)}{\sqrt{\text{Var}(X) \times \text{Var}(Y)}}, \\
& Y \sim \text{Binom}(1, prob = \mathcal{P}(X \geq a)) \implies Y \sim \text{Binom}(1, 1-a),\\
& \text{Var}(X) = \frac{1}{12}~, ~~\text{Var}(Y) = a \times (1-a), ~~ \mathcal{E}(X) = \frac{1}{2}, ~~\mathcal{E}(Y) = 1-a \implies\\
& \text{Cov}(X, Y) = \mathcal{E}(XY) - \mathcal{E}(X)\mathcal{E}(Y), \\
& \mathcal{E}(XY) = \int_{s_x}\sum_{y = 0}^1 xy f(x, y)~ d_x = \\
& \int_{s_x}xf(x, y = 1)~dx = \int_{s_x}xf(x, x \geq a)~dx = \int_a^1 xf(x)~dx \quad\quad\quad (i)\\
& = \int_a^1 x~dx = \frac{1-a^2}{2}\\
& \implies \text{Cov}(X, Y) = \frac{1-a^2}{2} - \frac{1}{2}\times (1-a) = \frac{1-a^2 -(1-a)}{2} = \frac{a(1-a)}{2}, \\
&\implies \text{Corr}(X, Y) = \frac{\frac{a(1-a)}{2}}{\sqrt{\frac{1}{12}\times a(1-a)}} = \sqrt{3} \times \sqrt{a(1-a)}\\
& \underset{a}{\argmax} ~~\sqrt{3} \times \sqrt{a(1-a)} = \underset{a}{\argmax}~~ a(1-a) = \frac{1}{2} ~ ? \implies \\
& \max \text{Corr}(X, Y) = \sqrt{3}\times \sqrt{\frac{1}{2}\times (1 - \frac{1}{2})} = \frac{\sqrt{3}}{2}
\end{aligned}
$$

In [59]:
## python simulate

import numpy as np 
from scipy.stats import uniform
a, b = 0, 1
rv = uniform(a, b)
def q_70(n, a):
    x_sim = rv.rvs(size = n, random_state = 1234)
    y_sim = 1 * (x_sim >= a)
    temp1 = np.stack((x_sim, y_sim), axis = 0)
    cor_result = np.corrcoef(temp1)[0, 1]
    return cor_result

a = np.linspace(0, 1, 50)
a = a[1:(len(a)-1)] # remove 0, 1 
a = np.append(a, 1/2) # add 1/2
n = int(1e+6) # define number of iteration to simulate data
q_70 = np.vectorize(q_70)
Result = q_70(n = n, a = a)
print("""
max of correlation between X and Y       : {:.4f}, \n
and value of a that make max correlation : {:.4f}, \n
sqrt(3)/2                                : {:.4f}.
""".format(Result.max(), a[Result.argmax()], np.sqrt(3)/2))


max of correlation between X and Y       : 0.8659, 

and value of a that make max correlation : 0.5000, 

sqrt(3)/2                                : 0.8660.



<hr><hr>

<br><br>

### Problem 69


### Ansewer is Option 3 --->
<br><br>
$$
\begin{aligned}
& \text{if}~~ X\sim F, ~~ \mathcal{P}(X \geq 0) = 1, ~~ \mathcal{E}(X^2) < +\infty,  ~~ 0 < a < 1 \implies \\
& \text{Recursive Method}: ~~ \mathcal{E}(X) \leq \mathcal{E}(X\text{I}_{\left\{X > a\mathcal{E}(X)\right\}})  \\
& \underset{\text{Problem 70}}{(i)} \implies \int_0^\infty xf(x)dx \leq \int_{a\mathcal{E}(X)}^\infty xf(x)dx\implies \\
& \int_{0}^{a\mathcal{E}(X)}xf(x)dx \leq 0 ~~\boldsymbol{{\Large \therefore}}\\
& \mathcal{P}(X = 0) = 1 \lor a = 0\quad \text{False}
\end{aligned}
$$

<hr><hr>
<br><br><br>


### Problem 68 


$$
\newcommand{\ind}{\perp\!\!\!\!\perp} 
\begin{aligned}
&\text{let}~~ X_i \overset{iid}{\sim}\mathcal{N}(0, 1), \quad i = 1, 2. \\
& U \sim \text{Unif}(0, 1) ~~\text{and}~~ U \ind X_i, \quad i = 1, 2. \\
\end{aligned}
$$

$$
\begin{aligned}
& Z = UX_1 + (1-U)X_2 \implies \text{Var}(Z) = ?
\end{aligned}
$$

### Answer


$$
\begin{aligned}
& \mathcal{E}(X_1) = \mathcal{E}(X_2) = 0, ~~ \mathcal{E}(U) = \frac{1}{2}, ~~\mathcal{E}(X_1^2) = \mathcal{E}(X_2^2) = 1, ~~ \mathcal{E}(U^2) = \frac{1}{3}\\
& \text{Var}(Z) = \mathcal{E}(Z^2) - \mathcal{E}(Z)^2 = \mathcal{E}((UX_1 + (1-U)X_2)^2) - (\mathcal{E}(UX_1 + (1-U)X_2))^2 = \\
& \mathcal{E}(U^2 X_1 ^2 - 2U^2 X_1 X_2 + U^2 X_2 ^2 + 2U X_1 X_2 - 2UX_2 ^2 + X_2 ^2)-0 = \\
& \frac{1}{3}\times 1 -0 + \frac{1}{3}\times 1 -2\times \frac{1}{2}\times 1 + 1 = \frac{2}{3}
\end{aligned}
$$

In [62]:
from sympy import *
u, x1, x2 = symbols('u x_1 x_2')

In [65]:
a = (u*x1 + (1-u) * x2)
expand(a**2)

u**2*x_1**2 - 2*u**2*x_1*x_2 + u**2*x_2**2 + 2*u*x_1*x_2 - 2*u*x_2**2 + x_2**2

In [13]:
g1 = [1, 2, 3]
g2 = [2, 3, 5]
g3 = np.stack((g1, g2), axis = 0)
g4 = np.cov(g3)
g1 = np.asarray(g1)
g2 = np.asarray(g2)

print(g3, "\n\n\n", g4, "\n\n\n", np.corrcoef(g3), "\n\n\n", g1.mean())


[[1 2 3]
 [2 3 5]] 


 [[1.         1.5       ]
 [1.5        2.33333333]] 


 [[1.         0.98198051]
 [0.98198051 1.        ]] 


 2.0
